wthrly/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("wthrlyapp.urls"))
]

wthrlyapp/urls.py
from django.urls import path
from . import views

app_name = "wthrlyapp"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:oras>/", views.localitate, name="localitate"),
    path("<str:oras>/addFav/", views.addFav, name="addFav"),
    path("auth/login/", views.login_view, name="login"),
    path("auth/logout/", views.logout_view, name="logout"),
    path("auth/signup/", views.signup_view, name="signup"),
]

wthrlyapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100)

wthrlyapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Favorite
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django import forms
from urllib.parse import unquote
from django.contrib.auth.decorators import login_required

PREDEFINED_CITIES = ["Timisoara", "New York", "Dubai"]

class SignupForm(forms.Form):
    username = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(required=True)
    password1 = forms.CharField(widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(widget=forms.PasswordInput, required=True)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("This username is already taken. Please choose a different one.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("An account linked to this email already exists.")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords do not match")
        return password2

    def save(self):
        username = self.cleaned_data['username']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password1']
        user = User.objects.create_user(username=username, email=email, password=password)
        return user

def index(request):
    if request.user.is_authenticated:
        favorites = Favorite.objects.filter(user=request.user)
    else:
        favorites = [{"city": city} for city in PREDEFINED_CITIES]
    return render(request, "wthrlyapp/index.html", {"favorites": favorites})

def localitate(request, oras):
    oras = unquote(oras)
    numberRange = range(9)
    isFav = False

    if request.user.is_authenticated:
        favorites = Favorite.objects.filter(user=request.user).values_list('city', flat=True)
        isFav = oras in favorites
        
    return render(request, "wthrlyapp/localitate.html", {"oras": oras, "numberRange": numberRange, "isFav": isFav})

@login_required
def addFav(request, oras):
    oras = unquote(oras)
    if not Favorite.objects.filter(user=request.user, city=oras).exists():
        Favorite.objects.create(user=request.user, city=oras)
    else:
        Favorite.objects.filter(user=request.user, city=oras).first().delete()
    return redirect('wthrlyapp:localitate', oras = oras)

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("wthrlyapp:index"))
        else:
            return render(request, "wthrlyapp/login.html", {
                "message": "Invalid Credentials"
            })

    return render(request, "wthrlyapp/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("wthrlyapp:index"))

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("wthrlyapp:index"))
        else:
            return render(request, 'wthrlyapp/signup.html', {'form': form})
    else:
        form = SignupForm()
    return render(request, 'wthrlyapp/signup.html', {'form': form})

wthrlyapp/templates/wthrlyapp/index.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Wthrly</title>
  <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@400;700&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'wthrlyapp/css/styles.css' %}">
  <script src="{% static 'wthrlyapp/js/jsindex.js' %}"></script>
  <script src="{% static 'wthrlyapp/js/jsaction.js' %}"></script>
</head>
<body>
  <header class="d-flex align-items-center justify-content-center shadow-sm" style="z-index: 1000; position: sticky; top:0">
    <div class="col-7 d-flex align-items-center justify-content-between p-1">

      <a href="{% url 'wthrlyapp:index'%}"><img src="{% static 'wthrlyapp/assets/wthr.jpg' %}" style="height:55px;width:auto"></a>

      <div class="dropdown d-flex justify-content-center align-items-center">
        <button class="btn btn-custom" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          <h2 class="m-0"><i class="bi bi-person"></i></h2>
          <h2 class="m-0"><i class="bi bi-person-fill"></i></h2>
        </button>
        <ul class="dropdown-menu dropdown-custom" aria-labelledby="dropdownMenuButton">
          {% if user.is_authenticated %}
          <li><a class="dropdown-item">Welcome, {{ request.user }}</a></li>
          <li><a class="dropdown-item" href="{% url 'wthrlyapp:logout' %}" style="color:red">Log out</a></li>
          {% else %}
          <li><a class="dropdown-item" href="{% url 'wthrlyapp:signup' %}">Sign Up</a></li>
          <li><a class="dropdown-item" href="{% url 'wthrlyapp:login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>

    </div>
  </div>
</header>

<div class="d-flex align-items-center p-5 justify-content-center" style="background-color:white;height:400px;background-image: url('../../static/wthrlyapp/assets/jos2.svg');">
  <form class="d-flex align-items-center justify-content-center col-3 flex-column" id="oras-form">
    <input class= "custom-input form-control" id="oras" placeholder="Enter your city" type="text" required autofocus>
    <div id="eroare"></div>
  </form>
</div>

<div class="d-flex align-items-center justify-content-center shadow" style = "background-color: #1A5E63;">
  <div class="d-flex align-items-center justify-content-center">
    <h1 class="p-1 mb-0" style = "color:white">Favorites</h1>
  </div>
</div>

<div class="d-flex align-items-center justify-content-center p-5 wmare"  style="background-color:#B1AAAA;min-height:430px;max-height:100vh;">
  <div class="d-flex col-7 align-items-center justify-content-center p-5">
    {% if favorites %}
    {% for favorite in favorites %}
    <a href="{% url 'wthrlyapp:localitate' favorite.city %}" class="rectangle-wrapper"><div class="p-3 m-3 rectangle-custom d-flex flex-column justify-content-between" >
      <div class="d-flex">
        <h2><i class="bi bi-geo-alt-fill" ></i></h2>
        <h2><i class="bi bi-geo-alt"></i></h2>
      </div>
      <div class="d-flex justify-content-end flex-column">
        <div>
          <h2>{{ favorite.city|title }}</h2>
        </div>
        <div class= "d-flex align-items-center justify-content-start infoScurt">
          <h3 id="iconExacta{{favorite.city|cut:' '}}" style="color:#fff"><i class='bi'></i></h3>
          <div class="ps-2 pb-2" id ="stringTempExacta{{favorite.city|cut:' '}}" style="font-size:2rem; color:#fff"></div>
        </div>
      </div>
    </div></a>
    {% endfor %}
    {% else %}
    <h4>No favorites to show.</h4>
    {% endif %}
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

wthrlyapp/templates/wthrlyapp/localitate.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{oras|capfirst}}-Wthrly</title>
  <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@400;700&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"></script>
  {% load static %}
  <link rel="stylesheet" href="{% static 'wthrlyapp/css/styles.css' %}">
  <script src="{% static 'wthrlyapp/js/jslocalitate.js' %}"></script>
  <script src="{% static 'wthrlyapp/js/jsaction.js' %}"></script>
</head>

<body>
  <header class="d-flex align-items-center justify-content-center shadow-sm" style="z-index: 1000; position: sticky; top:0">
    <div class="col-7 d-flex align-items-center justify-content-between p-1">

      <a href="{% url 'wthrlyapp:index'%}"><img src="{% static 'wthrlyapp/assets/wthr.jpg' %}" style="height:55px;width:auto"></a>

      <div class= "d-flex align-items-center justify-content-center gap-1"style="height:10px">
        <form class="d-flex align-items-center justify-content-center" id="oras-form" >
          <input class= "custom-input form-control" id="oras1" placeholder="Enter your city" type="text" required>
          <div id="eroare"></div>
        </form>

        <div class="dropdown d-flex justify-content-center align-items-center">
          <button class="btn btn-custom" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
            <h2 class="m-0"><i class="bi bi-person"></i></h2>
            <h2 class="m-0"><i class="bi bi-person-fill"></i></h2>
          </button>
          <ul class="dropdown-menu dropdown-custom" aria-labelledby="dropdownMenuButton">
            {% if user.is_authenticated %}
            <li><a class="dropdown-item">Welcome, {{ request.user }}</a></li>
            <li><a class="dropdown-item" href="{% url 'wthrlyapp:logout' %}" style="color:red">Log out</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'wthrlyapp:signup' %}">Sign Up</a></li>
            <li><a class="dropdown-item" href="{% url 'wthrlyapp:login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>

      </div>
    </div>
  </header>

  <div class="d-flex my-5 align-items-center justify-content-center" >
    <div class="d-flex col-7 align-items-center justify-content-between">
      <div class="d-flex col-3 align-items-start justify-content-start">
        <div class="d-flex align-items-start justify-content-center flex-column">
          <div class="d-flex  align-items-center justify-content-start col-3">
            <h1 style ="text-transform:capitalize">{{oras}}</h1>
            {% if user.is_authenticated %}
            <form id="favForm" method="POST" action="{% url 'wthrlyapp:addFav' oras=oras %}">
              {% csrf_token %}
              <button class="btn btn-custom px-2" type="button" id="butonFav">
                {% if not isFav %}
                <div class="d-flex notFav">
                  <h3 class="pb-1"><i class="bi bi-star-fill"></i></h3>
                  <h3 class="pb-1"><i class="bi bi-star"></i></h3>
                </div>
                {% else %}
                <div class="d-flex Fav">
                  <h3 class="pb-1"><i class="bi bi-star-fill"></i></h3>
                  <h3 class="pb-1"><i class="bi bi-star"></i></h3>
                </div>
                {% endif %}
              </button>
            </form>
            {% endif %}
          </div>
          <div class="d-flex align-items-center justify-content-start">
            <h1 class = "ps-1" id="iconExacta" style="font-size:2rem;color:#1A5E63;"><i class='bi'></i></h1>
            <div class="ps-2 pb-2" id = "stringTempExacta" style="font-size:2rem"></div>
          </div>

          <div class="d-flex align-items-start justify-content-center flex-column">
            <div class = "ps-1" id = "stringUmiditate" style="font-size:1.2rem"></div>
            <div class = "ps-1" id = "stringVant" style="font-size:1.2rem"></div>
          </div>
        </div>
      </div>
      <div class="d-flex flex-column align-items-center justify-content-start" style="padding-top:38px" >
        <div id = "stringOraExacta" style="font-size:2rem"></div>
        <div id = "stringVremeExacta" style="font-size:2rem"></div>
      </div>
    </div>
  </div>

  <div class="d-flex my-5 p-2 align-items-center justify-content-center" >
    <div class="d-flex col-7 my-5 flex-column justify-content-start">
      <div class="d-flex align-items-center justify-content-start">
        <h1>3-Hour Forecast</h1>
      </div>
      <div class="d-flex align-items-center justify-content-start scroll" style="overflow:hidden;overflow-x:auto;scroll-snap-type: x mandatory;">
        {% for i in numberRange %}
        <div class="d-flex pe-5 align-items-center justify-content-center flex-column">
          <div id = "stringOre{{i}}" style="font-size:2rem"></div>
          <div class="d-flex  align-items-center justify-content-center">
            <h3 id="icoane{{i}}" style="color:#1A5E63;"><i class='bi'></i></h3>
            <div id = "stringTemperaturi{{i}}" class="pb-2 ps-1" style="font-size:2rem"></div>
          </div>
        </div>
        {% endfor %}
        <div class="d-flex align-items-center justify-content-center flex-column">
          <div id = "stringOre9" style="font-size:2rem"></div>
          <div class="d-flex  align-items-center justify-content-center">
            <h3 id="icoane9" style="color:#1A5E63;"><i class='bi'></i></h3>
            <div id = "stringTemperaturi9" class="pb-2 ps-1" style="font-size:2rem"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="d-flex align-items-center justify-content-center wmare pb-5" style="background-color:#B1AAAA; min-height:600px">
    <div class= "col-7">
      <h1 class= "pb-2">Weather Map</h1>
      <div class="d-flex  align-items-center justify-content-center flex-column">
        <h3>Precipitations Map</h3>
        <div id="map" style="height:600px;width:600px"></div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

wthrlyapp/templates/wthrlyapp/login.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'wthrlyapp/css/styles.css' %}">
</head>
<body>
    <header class="d-flex align-items-center justify-content-center shadow-sm" style="z-index: 1000; position: sticky; top:0;">
        <div class="col-7 d-flex p-2 align-items-center justify-content-between">
            <a href="{% url 'wthrlyapp:index'%}"><img src="{% static 'wthrlyapp/assets/wthr.jpg' %}" style="height:55px;width:auto"></a>
            <div class="dropdown">
                <button  class="btn btn-custom mt-2" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                    <h2><i class="bi bi-person"></i></h2>
                    <h2><i class="bi bi-person-fill"></i></h2>
                </button>
                <ul class="dropdown-menu dropdown-custom" aria-labelledby="dropdownMenuButton">
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item">Welcome, {{ request.user }}</a></li>
                    <li><a class="dropdown-item" href="{% url 'wthrlyapp:logout' %}" style="color:red">Log out</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'wthrlyapp:signup' %}">Sign Up</a></li>
                    <li><a class="dropdown-item" href="{% url 'wthrlyapp:login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>
    <div class="d-flex align-items-center justify-content-center" style="background-image: url('https://raw.githubusercontent.com/PurzaVlad/WTHRLY/main/jos2.svg');height:90vh">
        <div class="d-flex col-3 align-items-center justify-content-center shadow-sm flex-column" style="background-color:#B1AAAA;border-radius: 25px;">
            <form class="d-flex align-items-center justify-content-center flex-column" action="{% url 'wthrlyapp:login' %}" method="post">
                {% csrf_token %}
                <input class="mt-5 mb-1 form-control rounded-pill custom-input form" type="text" name="username" placeholder="Username">
                <input class="m-1 form-control rounded-pill custom-input form" type="password" name="password" placeholder="Password">
                <input class="m-2 p-1 btn-custom rounded-pill" style="background-color:white;height:30px" type="submit" value="Login">
            </form>
            {% if message %}
            <p class="mt-3">{{message}}</p>
            {% endif %}
            <p class="mt-5">Don`t already have an account?<a href="{% url 'wthrlyapp:signup' %}">Sign up!</a></p>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

wthrlyapp/templates/wthrlyapp/signup.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'wthrlyapp/css/styles.css' %}">
</head>
<body>
    <header class="d-flex align-items-center justify-content-center shadow-sm" style="z-index: 1000; position: sticky; top:0;">
        <div class="col-7 d-flex p-2 align-items-center justify-content-between">
            <a href="{% url 'wthrlyapp:index'%}"><img src="{% static 'wthrlyapp/assets/wthr.jpg' %}" style="height:55px;width:auto"></a>
            <div class="dropdown">
                <button  class="btn btn-custom mt-2" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"  data-bs-target="#dropdownMenu">
                    <h2><i class="bi bi-person"></i></h2>
                    <h2><i class="bi bi-person-fill"></i></h2>
                </button>
                <ul class="dropdown-menu dropdown-custom" aria-labelledby="dropdownMenuButton">
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item">Welcome, {{ request.user }}</a></li>
                    <li><a class="dropdown-item" href="{% url 'wthrlyapp:logout' %}" style="color:red">Log out</a></li>
                    {% else %}
                    <li><a class="dropdown-item" href="{% url 'wthrlyapp:signup' %}">Sign Up</a></li>
                    <li><a class="dropdown-item" href="{% url 'wthrlyapp:login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>
    <div class="d-flex align-items-center justify-content-center" style="background-image: url('https://raw.githubusercontent.com/PurzaVlad/WTHRLY/main/jos2.svg');height:90vh">
        <div class="d-flex col-3 align-items-center justify-content-center shadow-sm flex-column" style="background-color:#B1AAAA; border-radius: 25px;">
            <form class="d-flex align-items-center justify-content-center flex-column" action="{% url 'wthrlyapp:signup' %}" method="post">
                {% csrf_token %}
                <input class="mt-5 mb-1 form-control rounded-pill custom-input form" type="text" name="username" placeholder="Username">
                <input class="m-1 form-control rounded-pill custom-input form" type="email" name="email" placeholder="Email">
                <input class="m-1 form-control rounded-pill custom-input form" type="password" name="password1" placeholder="Password">
                <input class="m-1 form-control rounded-pill custom-input form" type="password" name="password2" placeholder="Password Confirmation">
                <input class="m-2 p-1 btn-custom rounded-pill" style="background-color:white;height:30px" type="submit" value="Signup">
            </form>
            {% if form.errors %}
            <div class="errors">
                {% for field in form %}
                {% for error in field.errors %}
                <p class="mt-2">{{ error }}</p>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <p class="mt-5">{{ error }}</p>
                {% endfor %}
            </div>
            {% endif %}
            <p class="mt-5">Already have an account?<a href="{% url 'wthrlyapp:login' %}">Log in!</a></p>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>